forum/urls.py
from . import views
from django.urls import path

app_name = 'forum'

urlpatterns = [
    path('post/<int:post_pk>/', views.PostPageView.as_view(), name='post_page'),
    path('post/edit/<int:post_pk>/', views.PostEditView.as_view(), name='post_edit'),
    path('post/delete/<int:post_pk>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),

    # Comments
    path('comment/<int:comment_pk>/edit/', views.CommentEditView.as_view(), name='comment_edit'),
    path('comment/<int:comment_pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),

    # Categories
    path('category/<str:category_title>/', views.CategoryPostsView.as_view(), name='category_posts'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
	path('', views.HomepageView.as_view(), name='homepage'),
	path('search/', views.SearchView.as_view(), name='search_posts'),
	path('search/<str:category_title>/', views.SearchView.as_view(), name='search_category_posts'),
]

project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

handler400 = 'main.views.http400'
handler403 = 'main.views.http403'
handler404 = 'main.views.http404'
handler500 = 'main.views.http500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('rest_api.urls')),
    path('user/', include('users.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('forum/', include('forum.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.AuthenticationView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('email/<str:status>/', views.ConfirmEmailView.as_view(), name='email_confirm'),
    path('profile/settings/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('profile/<str:username>/', views.ProfileView.as_view(), name='profile'),

    # Password reset
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset_password_sent/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Password change
    path('password_change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.CustomPasswordChangeDoneView.as_view(), name='password_change_done'),

    # Change email
    path('email_change/verification/', views.ProfileVerificationView.as_view(), name='email_change_verification'),
    path('email_change/confirm/', views.ChangeEmailConfirmView.as_view(), name='email_change_confirm'),
    path('email_change/new_email/<str:status>/', views.ConfirmNewEmailView.as_view(),
         name='email_change_confirm_new_email'),
]

templates/users/password/password_reset/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

<p>Password successfully reset</p>

{% endblock %}

templates/users/password/password_reset/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {% include 'form/fields_render.html' %}
    <input type="submit" value="Reset">
</form>

{% endblock %}

templates/users/password/password_reset/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

<p>Check your email</p>

{% endblock %}

templates/users/password/password_reset/password_reset_email.html
{% autoescape on %}
<p>You're receiving this e-mail because you requested a password reset for your user account at {{ site_name }}.

<p>Please go to the following page and choose a new password:

{% block reset_link %}
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">Reset link</a>
{% endblock %}

<p>Your username, in case you've forgotten: {{ username }}

<p>Thanks for using our site!
{% endautoescape %}

templates/users/password/password_reset/password_reset_form.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {% include 'form/fields_render.html' %}
    <input class="btn btn-dark mt-4" type="submit" value="Send">
</form>

{% endblock %}