forum/urls.py
from . import views
from django.urls import path

app_name = 'forum'

urlpatterns = [
    path('post/<int:post_pk>/', views.PostPageView.as_view(), name='post_page'),
    path('post/edit/<int:post_pk>/', views.PostEditView.as_view(), name='post_edit'),
    path('post/delete/<int:post_pk>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),

    # Comments
    path('comment/<int:comment_pk>/edit/', views.CommentEditView.as_view(), name='comment_edit'),
    path('comment/<int:comment_pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),

    # Categories
    path('category/<str:category_title>/', views.CategoryPostsView.as_view(), name='category_posts'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
	path('', views.HomepageView.as_view(), name='homepage'),
	path('search/', views.SearchView.as_view(), name='search_posts'),
	path('search/<str:category_title>/', views.SearchView.as_view(), name='search_category_posts'),
]

project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

handler400 = 'main.views.http400'
handler403 = 'main.views.http403'
handler404 = 'main.views.http404'
handler500 = 'main.views.http500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('rest_api.urls')),
    path('user/', include('users.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('forum/', include('forum.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.AuthenticationView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('email/<str:status>/', views.ConfirmEmailView.as_view(), name='email_confirm'),
    path('profile/settings/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('profile/<str:username>/', views.ProfileView.as_view(), name='profile'),

    # Password reset
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset_password_sent/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Password change
    path('password_change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.CustomPasswordChangeDoneView.as_view(), name='password_change_done'),

    # Change email
    path('email_change/verification/', views.ProfileVerificationView.as_view(), name='email_change_verification'),
    path('email_change/confirm/', views.ChangeEmailConfirmView.as_view(), name='email_change_confirm'),
    path('email_change/new_email/<str:status>/', views.ConfirmNewEmailView.as_view(),
         name='email_change_confirm_new_email'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Forum</title>
    {% endif %}
    <link type="text/css" rel="stylesheet" href="{% static 'bootstrap_css/bootstrap.css' %}">
    <link rel="icon" type="imagex/x-icon" href="{% static 'img/favicon.ico' %}">
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</head>

<body>

<header class="p-2 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a class="fs-4 text-white me-auto" href="{% url 'main:homepage' %}">
                <img src="{% static 'img/logo.jpg' %}"><span class="ms-1">Forum</span>
            </a>
            <div id="auth_links" class="text-end">
                {% if user.is_authenticated %}
                    <a class="fs-5 text-white me-3" href="{{ user.get_absolute_url }}">{{ user.username }}</a>
                    <a class="btn btn-danger" href="{% url 'users:logout' %}">Logout</a>
                {% else %}
                    <a class="btn btn-outline-light me-2" href="{% url 'users:login' %}">Login</a>
                    <a class="btn btn-warning" href="{% url 'users:signup' %}">SignUp</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="mt-3">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>
    {% block content %}
    {% endblock %}
</div>

<footer class="pt-5">
</footer>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
    <div class="d-flex justify-content-between mt-2 mb-1">
        <a class="btn btn-success" href="{% url 'forum:post_create' %}">Add post</a>
        <form method="get" action="{% if selected_category %}{% url 'main:search_category_posts' selected_category.title %}{% else %}{% url 'main:search_posts' %}{% endif %}">
            <div class="input-group">
                <input class="form-control w-50 rounded" type="search" name="q">
                <button type="submit" class="btn btn-outline-primary">Search</button>
            </div>
        </form>
    </div>
{% endif %}

<div class="d-flex justify-content-between">
    <div id="posts_list" class="w-70 d-inline-block">
        {% if posts %}
            <div class="border-top border-right border-left mt-3 p-3 bg-dark"></div>
            {% for post in posts %}
                <div class="border border-secondary pt-1 pb-1 ps-3">
                    <a href="{% url 'forum:post_page' post.pk %}">{{ post.title }}</a>
                </div>
            {% endfor %}
        {% else %}
            <h3 class="text-center">There are no posts yet.</h3>
        {% endif %}
    </div>

    <div id="categories_list" class="fw-bold w-20 d-inline-block">
            {% if categories %}
            <div class="border-top border-right border-left mt-3 p-3 bg-dark"></div>
            {% for category in categories %}
                {% if category.pk == selected_category.pk %}
                    <div style="overflow:hidden;" class="border border-secondary bg-secondary pt-1 pb-1 ps-2">
                        <a href="{% url 'forum:category_posts' category.title %}" class="text-white">{{ category.title }}</a>
                    </div>
                {% else %}
                    <div class="border border-secondary pt-1 pb-1 ps-2">
                        <a class="link-secondary" href="{% url 'forum:category_posts' category.title %}">{{ category.title }}</a>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</div>

{% if page_obj.has_other_pages %}
    <div class="border bg-dark text-white mt-4 p-1">
        {% for page_number in paginator.page_range %}
            {% if page_number == page_obj.number %}
                <span class="ms-2">{{ page_number }}</span>
            {% elif page_number >= page_obj.number|add:-3 and page_number <= page_obj.number|add:5 %}
                <a class="btn btn-warning ms-2" href="?page={{ page_number }}">{{ page_number }}</a>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}

{% endblock %}