forum/urls.py
from . import views
from django.urls import path

app_name = 'forum'

urlpatterns = [
    path('post/<int:post_pk>/', views.PostPageView.as_view(), name='post_page'),
    path('post/edit/<int:post_pk>/', views.PostEditView.as_view(), name='post_edit'),
    path('post/delete/<int:post_pk>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),

    # Comments
    path('comment/<int:comment_pk>/edit/', views.CommentEditView.as_view(), name='comment_edit'),
    path('comment/<int:comment_pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),

    # Categories
    path('category/<str:category_title>/', views.CategoryPostsView.as_view(), name='category_posts'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
	path('', views.HomepageView.as_view(), name='homepage'),
	path('search/', views.SearchView.as_view(), name='search_posts'),
	path('search/<str:category_title>/', views.SearchView.as_view(), name='search_category_posts'),
]

project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

handler400 = 'main.views.http400'
handler403 = 'main.views.http403'
handler404 = 'main.views.http404'
handler500 = 'main.views.http500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('rest_api.urls')),
    path('user/', include('users.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('forum/', include('forum.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rest_api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('posts/', views.PostAPI.as_view({'get': 'list'}), name='posts_all'),
    path(
        'post/<int:pk>/', views.PostAPI.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
        name='post_get_edit_delete'
    ),
    path('post/create/', views.PostAPI.as_view({'post': 'create'}), name='post_create'),
    path('post/<int:pk>/comments/', views.CommentAPI.as_view({'get': 'list'}), name='post_comments'),
    path('post/<int:pk>/<str:status>/', views.PostRatingAPI.as_view(), name='post_rating'),

    path(
        'comment/<int:pk>/', views.CommentAPI.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
        name='comment_get_edit_delete'
    ),
    path('comment/<int:pk>/<str:status>/', views.CommentRatingAPI.as_view(), name='comment_rating'),
    path('comment/create/', views.CommentAPI.as_view({'post': 'create'}), name='comment_create'),

    path('categories/', views.CategoryAPI.as_view({'get': 'list'}), name='categories_list'),
    path('category/<int:pk>/', views.CategoryAPI.as_view({'get': 'retrieve'}), name='category_posts'),

    path('user/<str:username>/posts/', views.UserPostsAPI.as_view(), name='user_posts'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.AuthenticationView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('email/<str:status>/', views.ConfirmEmailView.as_view(), name='email_confirm'),
    path('profile/settings/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('profile/<str:username>/', views.ProfileView.as_view(), name='profile'),

    # Password reset
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset_password_sent/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Password change
    path('password_change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.CustomPasswordChangeDoneView.as_view(), name='password_change_done'),

    # Change email
    path('email_change/verification/', views.ProfileVerificationView.as_view(), name='email_change_verification'),
    path('email_change/confirm/', views.ChangeEmailConfirmView.as_view(), name='email_change_confirm'),
    path('email_change/new_email/<str:status>/', views.ConfirmNewEmailView.as_view(),
         name='email_change_confirm_new_email'),
]

forum/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from users.models import CustomUserModel
from ckeditor.fields import RichTextField


class AbstractDateAndRating(models.Model):
    published_date = models.DateTimeField(auto_now_add=True)
    last_change_date = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(CustomUserModel, related_name='%(class)ss_likes', blank=True)
    dislikes = models.ManyToManyField(CustomUserModel, related_name='%(class)ss_dislikes', blank=True)

    class Meta:
        abstract = True


class Category(models.Model):
    title = models.CharField(max_length=255, unique=True)

    class Meta:
        db_table = 'categories'
        verbose_name_plural = 'Categories'
        ordering = ['-pk']

    def __str__(self):
        return self.title

    def clean(self):
        if len(self.title.split(' ')) > 1:
            raise ValidationError('The title must be united. Example "%s"' % ('-'.join(self.title.split(' '))))
        super(Category, self).clean()


class Post(AbstractDateAndRating):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = RichTextField(max_length=20000)
    author = models.ForeignKey(CustomUserModel, on_delete=models.CASCADE)

    class Meta:
        db_table = 'posts'
        ordering = ['-published_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('forum:post_page', kwargs={'post_pk': self.pk})


class Comment(AbstractDateAndRating):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField(max_length=1500)
    author = models.ForeignKey(CustomUserModel, on_delete=models.CASCADE)

    class Meta:
        db_table = 'comments'
        ordering = ['-published_date']

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('forum:post_page', kwargs={'post_pk': self.post.pk}) + f'#comment_{self.pk}'

forum/forms.py
from django import forms
from .models import Post, Comment


class CreateAndEditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'category', 'content']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select form-select-sm'})
        }


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = 'Comment'

    class Meta:
        model = Comment
        fields = ['text']

        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'style': 'resize:none'})
        }

forum/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import DetailView, CreateView, DeleteView, UpdateView, ListView
from django.views.generic.edit import FormMixin
from .models import Post, Comment, Category
from .forms import CreateAndEditPostForm, CommentForm
from django.contrib import messages
from .utils import CategoryContextMixin


@method_decorator(login_required, name='post')
class PostPageView(FormMixin, DetailView):
    model = Post
    template_name = 'forum/post_page.html'
    form_class = CommentForm
    pk_url_kwarg = 'post_pk'
    paginate_by = 30

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(PostPageView, self).get_context_data(**kwargs)
        context['paginator'] = Paginator(
            self.object.comment_set.all().select_related('author').prefetch_related('likes', 'dislikes'),
            self.paginate_by
        )
        context['page_obj'] = self.get_page_obj(context['paginator'], self.request.GET.get('page', 1))
        return context

    def get_page_obj(self, paginator, page_number):
        page_obj = paginator.page(page_number)
        return page_obj

    def form_valid(self, form):
        form.instance.post = self.object
        form.instance.author = self.request.user
        form.save()
        return HttpResponseRedirect(self.object.get_absolute_url())


@method_decorator(login_required, name='dispatch')
class PostCreateView(CreateView):
    template_name = 'forum/post_create_and_edit.html'
    form_class = CreateAndEditPostForm

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostCreateView, self).form_valid(form)


class PostEditView(UpdateView):
    model = Post
    template_name = 'forum/post_create_and_edit.html'
    form_class = CreateAndEditPostForm
    pk_url_kwarg = 'post_pk'

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().author == self.request.user:
            return super(PostEditView, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


@method_decorator(require_POST, name='dispatch')
class PostDeleteView(DeleteView):
    model = Post
    pk_url_kwarg = 'post_pk'
    success_url = reverse_lazy('main:homepage')

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().author == self.request.user:
            return super(PostDeleteView, self).post(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, 'Post was successfully deleted')
        return super(PostDeleteView, self).form_valid(form)


class CommentEditView(UpdateView):
    model = Comment
    template_name = 'forum/comment_edit.html'
    form_class = CommentForm
    pk_url_kwarg = 'comment_pk'

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().author == self.request.user:
            return super(CommentEditView, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(self.object.get_absolute_url())


@method_decorator(require_POST, name='dispatch')
class CommentDeleteView(DeleteView):
    model = Comment
    pk_url_kwarg = 'comment_pk'

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().author == self.request.user:
            return super(CommentDeleteView, self).post(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        self.object.delete()
        messages.add_message(self.request, messages.SUCCESS, 'Comment was successfully deleted')
        return HttpResponseRedirect(self.object.get_absolute_url())


class CategoryPostsView(CategoryContextMixin, ListView):
    context_object_name = 'posts'
    template_name = 'index.html'
    paginate_by = 30

    def get_queryset(self):
        return Post.objects.filter(
            category__title=self.kwargs['category_title'], published_date__lte=timezone.now()
        ).values('title', 'pk')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryPostsView, self).get_context_data(**kwargs)
        category_context = self.get_category_context(
            selected_category=get_object_or_404(Category, title=self.kwargs['category_title']))
        context = dict(list(context.items()) + list(category_context.items()))
        return context

templates/forum/comment_edit.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {% include 'form/fields_render.html' %}
  <input class="btn btn-secondary mt-2" type="submit" value="Edit">
</form>
{% endblock %}

templates/forum/post_create_and_edit.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {% include 'form/fields_render.html' %}
    <input name="button" class="btn btn-success mt-4" type="submit">
</form>

<script>
    const form = document.forms[0]
    const textArea = form.elements['content']

    if (textArea.value){
        form.button.value = 'Edit'
    }
    else{
        form.button.value = 'Create'
    }
</script>

{% endblock %}

templates/forum/post_page.html
{% extends 'base.html' %}

{% block content %}

<!-- Post content -->
<div class="post">
    <div style="overflow:hidden;" class="mt-3 mb-4 h2">
        <h4>{{ post.title }}</h4>
    </div>
    <div class="mt-2 mb-5 h5">
        {{ post.content|safe }}
    </div>
    <div>
        <h6>Author: <a href="{% url 'users:profile' post.author.username %}">{{ post.author }}</a></h6>
    </div>
    <div>
        <h6>Posted: {{ post.published_date }}</h6>
        {% if post.last_change_date != post.published_date %}
            <h6>Last Change Date: {{ post.last_change_date }}</h6>
        {% endif %}
    </div>

    <!-- Like and Dislike buttons -->
    <div>
        <form name="post_rating_form">
            {% csrf_token %}
            <input class="btn btn-success" action="{% url 'api:post_rating' pk=post.pk status='like' %}" type="submit" name="post_like" value="&uarr; {{ post.likes.count }}">
            <input class="btn btn-danger" action="{% url 'api:post_rating' pk=post.pk status='dislike' %}" type="submit" name="post_dislike" value="&darr; {{ post.dislikes.count }}">
        </form>
    </div>
</div>

{% if user == post.author %}
    <div class="d-flex mb-3 mt-3">
        <form name="post_delete_form" class="me-2" method="post" action="{% url 'forum:post_delete' post.pk %}">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Delete">
        </form>
        <a class="btn btn-primary" href="{% url 'forum:post_edit' post.pk %}">Edit</a>
    </div>
{% endif %}

<!-- Comment form -->
{% if user.is_authenticated %}
    <form method="post">
        {% csrf_token %}
        {% include 'form/fields_render.html' %}
        <input class="btn btn-secondary mt-2" type="submit" value="Post">
    </form>
{% else %}
    <p class="mt-2 mb-2"><a href="{% url 'users:login' %}">Login</a> for post comment!</p>
{% endif %}

<!-- Comments -->
{% for comment in page_obj.object_list %}
    <div id="comment_{{ comment.pk }}" class="border border-dark rounded mt-3 pt-1 pe-3 ps-3">
        <div class="d-flex justify-content-between">
            <a href="{% url 'users:profile' comment.author.username %}">
                <img class="border border-dark" src="{{ comment.author.profile_image.url }}" width="50" height="50">
                <span class="align-top">{{ comment.author.username }}</span>
            </a>
            {% if user == comment.author %}
                <div class="d-flex">
                    <form class="me-2" name="commentDeleteForm" method="post" action="{% url 'forum:comment_delete' comment.pk %}">
                        {% csrf_token %}
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                    <div>
                        <a class="btn btn-primary" href="{% url 'forum:comment_edit' comment.pk %}">Edit</a>
                    </div>
                </div>
            {% endif %}
        </div>
        <div></div>
        <p class="mt-2"><span>{{ comment.text }}</span></p>
        <p>Posted: <span class="fw-bold">{{ comment.published_date }}</span></p>
        {% if comment.last_change_date != comment.published_date %}
            <p>Last Change Date: <span class="fw-bold">{{ comment.last_change_date }}</span></p>
        {% endif %}
        <form class="mb-1" name="comment_rating_form">
            <!--Jquery will take CSRF from 'post_rating_form'-->
            <input class="btn btn-success" action="{% url 'api:comment_rating' pk=comment.pk status='like' %}" type="submit" name="comment_like" value="&uarr; {{ comment.likes.count }}">
            <input class="btn btn-danger" action="{% url 'api:comment_rating' pk=comment.pk status='dislike' %}" type="submit" name="comment_dislike" value="&darr; {{ comment.dislikes.count }}">
        </form>
    </div>
{% endfor %}

<!-- Pagination -->
{% if page_obj.has_other_pages %}
    <div class="border bg-dark text-white mt-4 p-1">
        {% for page_number in paginator.page_range %}
            {% if page_number == page_obj.number %}
                <span class="ms-2">{{ page_number }}</span>
            {% elif page_number >= page_obj.number|add:-3 and page_number <= page_obj.number|add:5 %}
                <a class="btn btn-warning ms-2" href="?page={{ page_number }}">{{ page_number }}</a>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}

{% endblock %}